.TH WOLKEN 1 "Jun 3, 2011"
.SH "NAME"
wolken \- Clouds watching system.
.SH "SYNOPSIS"
.B wolken
.SH "DESCRIPTION"
.PP
.B wolken
Image capture application for Wolken project.
.SH "AUTHOR"
wolken was written by Juan Roldan Ruiz <juan@shoden.es>.
.PP
This manual page was written by Juan Roldan Ruiz <juan@shoden.es>,
for the Debian project (and may be used by others).
